Repository ipfs/ipfs-companion, pull requests merged in 2018-03, with the labels that each got.

#412 Docs reorganization
  CONTRIBUTING.md
  README.md
  docs/brave.md
  docs/developer-notes.md
  docs/firefox-for-android.md
  docs/window.ipfs.md
Labels: UX

#429 Fix options_ui in OSX Chrome
  add-on/src/options/options.css
  add-on/src/options/options.js
Labels: UX, bug

#430 fix: time till browser action dropdown appears
  add-on/src/popup/browser-action/index.html
  add-on/src/popup/page-action/index.html
  add-on/src/popup/quick-upload.html
  package.json
Labels: P1 - High, UX

#428 Decouple Page Action Updates
  add-on/_locales/en/messages.json
  add-on/src/popup/browser-action/browser-action.css
  add-on/src/popup/browser-action/context-actions.js
  add-on/src/popup/browser-action/gateway-status.js
  add-on/src/popup/browser-action/header.js
  add-on/src/popup/browser-action/operations.js
  add-on/src/popup/browser-action/store.js
  add-on/src/popup/page-action/header.js
Labels: UX

#435 Locale fixes and documentation
  CONTRIBUTING.md
  add-on/_locales/de/messages.json
  add-on/_locales/es/messages.json
  add-on/_locales/fr/messages.json
  add-on/_locales/id-AC/messages.json
  add-on/_locales/id/messages.json
  add-on/_locales/it/messages.json
  add-on/_locales/pl/messages.json
  add-on/_locales/ro/messages.json
  add-on/_locales/ru/messages.json
  add-on/_locales/sv/messages.json
  add-on/_locales/zh/messages.json
  docs/developer-notes.md
  docs/localization-notes.md
Labels: UX
