Repository ipfs/ipfs-companion, pull requests merged in 2018-06, with the labels that each got.

#497 Add Lead Maintainer
  README.md
  package.json
Labels: maintenance

#499 refactor: move content script build to webpack
  add-on/manifest.common.json
  add-on/src/background/big-deps.js
  add-on/src/contentScripts/ipfs-proxy/content.js
  add-on/src/contentScripts/linkifyDOM.js
  add-on/src/lib/ipfs-companion.js
  package.json
  webpack.config.js
  yarn.lock
Labels: maintenance

#500 Feature: ON / OFF Toggle
  add-on/_locales/en/messages.json
  add-on/src/lib/ipfs-companion.js
  add-on/src/lib/ipfs-request.js
  add-on/src/lib/options.js
  add-on/src/lib/state.js
  add-on/src/options/forms/gateways-form.js
  add-on/src/options/forms/global-toggle-form.js
  add-on/src/options/forms/ipfs-node-form.js
  add-on/src/options/options.css
  add-on/src/options/page.js
  add-on/src/popup/browser-action/browser-action.css
  add-on/src/popup/browser-action/context-actions.js
  add-on/src/popup/browser-action/gateway-status.js
  add-on/src/popup/browser-action/header.js
  add-on/src/popup/browser-action/icon.js
  add-on/src/popup/browser-action/mdc.switch.css
  add-on/src/popup/browser-action/nav-item.js
  add-on/src/popup/browser-action/operations.js
  add-on/src/popup/browser-action/options-icon.js
  add-on/src/popup/browser-action/page.js
  add-on/src/popup/browser-action/power-icon.js
  add-on/src/popup/browser-action/store.js
  add-on/src/popup/logo.js
  add-on/src/popup/page-action/header.js
  add-on/src/popup/page-action/page.js
  package.json
  test/functional/lib/ipfs-request.test.js
  yarn.lock
Labels: UX

#492 chore: upgrade dependencies
  add-on/src/lib/ipfs-companion.js
  add-on/src/lib/ipfs-proxy/api-whitelist.json
  add-on/src/lib/ipfs-proxy/index.js
  package.json
  yarn.lock
Labels: in progress

#506 fix: icons hover
  add-on/src/popup/browser-action/icon.js
Labels: UX, bug, difficulty:easy
